name: CustomEnchantingAPI
version: 1.0.0
main: com.starshootercity.customenchanting.CustomEnchantingAPI
description: Custom Enchanting API for Paper plugins
api-version: '1.20'
author: cometcake575

commands:
  test:
    description: Test
    usage: /<command>
