name: CustomEnchantmentAPI
version: 1.0.0
main: com.starshootercity.customenchanting.CustomEnchantmentAPI
description: Custom Enchanting API for Paper plugins
api-version: '1.20'
author: cometcake575

permissions:
  customenchantment.admin:
    default: op
    description: Admin custom enchantment commands

commands:
  update:
    description: Update the enchantment display of your held item
    permission: customenchantment.admin
    usage: /<command>
  custom-enchant:
    description: Apply a custom enchantment to an item
    permission: customenchantment.admin
    usage: /<command> <enchantment> [<level>]
  force-enchant:
    description: Force apply a custom enchantment to an item
    permission: customenchantment.admin
    usage: /<command> <enchantment> [<level>]
